image: circleci/python:3.7-node-browsers

pipelines:
  default:
    - step:
        name: Install, Build & test 
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm run build
    - step:
        name: Build and Push Docker Image to Public ECR
        services:
          - docker
        caches:
          - docker
        script:
          
          # Install AWS CLI
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"  
          - unzip awscliv2.zip  
          - sudo ./aws/install  
          - rm -rf awscliv2.zip  
          - aws --version  

        
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=us-east-1  
          # aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l6k0x5k3
         
          - docker build -t public.ecr.aws/l6k0x5k3/demo/app:notus-nextjs-latest .
          - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l6k0x5k3
          - docker push public.ecr.aws/l6k0x5k3/demo/app:notus-nextjs-latest
          

     
    - step:
        name: Deploy to EKS
        script:
          - echo "Configuring kubectl"
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"  
          - unzip awscliv2.zip 
          - sudo ./aws/install  
          - rm -rf awscliv2.zip  

           
          - curl -LO "https://dl.k8s.io/release/v1.31.2/bin/linux/amd64/kubectl"
          - chmod +x ./kubectl  
          - sudo mv ./kubectl /usr/local/bin 
          - kubectl version --client 

         
          - aws --version  
          - aws eks update-kubeconfig --region eu-north-1 --name $EKS_CLUSTER_NAME
          - export KUBECONFIG=~/.kube/config
          - echo "Deploying application to EKS"
          - kubectl apply -f deployment.yml
          - kubectl apply -f service.yml 


        
